---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: airflow-operator
  namespace: sble-operators
spec:
  chart:
    spec:
      chart: airflow-operator
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: stackable-repository
      version: 0.0.0-dev
  interval: 1m0s
