---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: superset-operator
  namespace: sble-operators
spec:
  chart:
    spec:
      chart: superset-operator
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: stackable-repository-stable
      version: 23.7.0
  interval: 1m0s
