apiVersion: s3.stackable.tech/v1alpha1
kind: S3Connection
metadata:
  name: ionos
  namespace: platform
spec:
  host: s3-eu-central-2.ionoscloud.com # See https://api.ionos.com/docs/s3/v2/. Ping from Berlin (de/tlx) shows 11 ms to s3-eu-central-1.ionoscloud.com and 1 ms to s3-eu-central-2.ionoscloud.com
  port: 443
  tls:
    verification:
      server:
        caCert:
          webPki: {}
  credentials:
    secretClass: ionos-s3-credentials
---
apiVersion: secrets.stackable.tech/v1alpha1
kind: SecretClass
metadata:
  name: ionos-s3-credentials
spec:
  backend:
    k8sSearch:
      searchNamespace:
        pod: {}

