apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: trino-users
  namespace: platform
spec:
  encryptedData:
    admin: AgBsYOaq7x5r0da8x0K+TFyUzixdbRlMQVhKZ1jOFb3X3VV1PttlkhMchXh8VbEXkuMHscOzDTKMwJYQXYSXfzYxKhVI3PBjXE83qlD3GmzGD37qcCNQOOlf38s8w5YH3xIuw6dI7ZYiVxNsXLGzyU6Rle4YO+a6DSFrK47rQGcEdGq5yttcRNg+tGfkyiiFiomJFgpHM5033cpaKetO0vW5nQWQyIxvvvexaShXE2Z3oqTnVADYwXLjlOLV27eVlPVQy1fKKh5sIT4LZMtNHgYOZm2y73ipv9RNKMUwGjsVoVG3/WfsG4RkuCdPZCchdrIITH9gZNTyMPTj8393jUdy4RMgyyRp1yMk3wiPLqDI+vuZTkUxFm+eqHvynhhUobuD63n1s8EUavgsn+GWEiM7Q1y7P2u++6CWCpnXL1gmM2Wf2hg6FtxFMD/OsQnHknKMGAAv4IgLbXyZxTx9zRG8F5aNhznCgTnXGmKCwN4mm6GxFVVLUVnyLEF9rH8/oA2vKQYU5zZtrMWgGFE0s08Fg41a+8JzbBVqcp55pBZvRBmGCEwBEAMhMGKTh/KXamyIgBehmNBbYHo/t8uZaeM3DnXb9dOnIaVsVKNpODeU8I3jmSofXMTFwuIcMRqjWGt9qsWVU/6ThOF/R9g9LgVD/aqm9rjaYu210Oqe13qY2uhVwk2Wb8OBWJKyjAHN1SsGMxo4Ag==
    user: AgAxZfYV0ZaCWRbuDalDZ7nP5GqYhOTJcsc3q5pFXPKOTA6Zlt8P+eM2G1VAZVDY4b1nkVpXBFDQypBWqfORacYycViJAe2KAMWmHIbjPaWM7pVxGq5gCmqCbSl2Ufd2+kKGL4X2ql3TLC92BH3ml/NUaHaXC23g4SwidCXyNNh39zyQZPIiEWMCBEVroeMvuflx30Z781/BO5cbCgDkaphKTemkBxSzfpqeVIsiwTGX1iFfd79us1SwnJ4qADnoUKWcalFOKz6u36g0kQ7jdhDQ1XpSV+WegTcvBB1RvkTzfNTy7gx4GppZx6qj9uzm3EprKZyGlDONVRVVB2s70nHPbLzzz0b5oj8aNHYkTQJYg5U9uBmT6ccGbCSnkran1ZtBXL34Ep7fzUhR5R//JtATW0etrCQKZa3yn2COj87J9DHrB8RSc/gyYEYBfJvQipvSZMJg4mR27zP3NinehvnNqyLA+YlmJ6fRwmBw1q8haHN6IA7zL84VriY68SEWCSoY3/GVl/Ew6KSLClFtGHhT3T+IK0a4Mi5t1x1TuGfBcEc6nWGR9X41p+J9tTNikCxQhG/ZBUCWRUtazavbaJvgNbKE1fPrOaciY0VI+yTXA4OzPZeF0IHA6ho3ZofFsJlE1EYAZafCGzqKKoDSRv72P/uQrucTwGxldGghMTKErqVim/PMpDEOi4f4oGjh3ws3FXEZ
  template:
    metadata:
      creationTimestamp: null
      name: trino-users
      namespace: platform
    type: kubernetes.io/opaque

