apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: trino-users
  namespace: platform
spec:
  encryptedData:
    admin: AgAH+fEITVQkcj3hN5QlOagsV1iHJOI4bCiqP3ss6gwKX6yBSg3AQu4TCfZAe/GJhbwD11rxmwZohxiPR6HLmX2qHVCEu/BvBICfzBkjTfjIGR66S8YnU9tXkX5UtPeSdKerwqKg9URJKWpizXOVAnEtyFwjOPX5SwDWxY99KHxcr6uz7SIQeJ9U86hjNCIfk2m2lnjXUz3WpsBcSKbsn0/IN5A1q+SZAZ67uqlMYartiu+i+79B7plBVCFjzHzFIp5XIiCZeNgDks2BzSV47gxyJDN2aUYDvALnbih8yx3wri5r1GbsbMQ41I5o5DomB9aulk1auMpT98dO/TFXoRTECoocjFpk6mTZgclCk7AzN8jXKV1qtOXTqTYn2WmgIx9xVCpi9IdQMOoeTDiT0J0kKNH5NaQJoYbTnbpT48fiVPP9WAH5Zd3mzlUWF455beMNu+atQYe6os7JUSZ4R/cwZoIKds5tDPDNOWM5EmhEeqB0f4ZioHOS6kRQLX9IYeIq0xT4HAG0M4Zd8jaV7Y9aYoU4q6DTBTRUBHrD8JJ/VIY+OuV/R1AGbgX6NZoSefK9PO8KH1PTLm2yhS3bRUaDiQNdS90A2V1wlL63I0peYuiwJW0JiT40cIM8xdwwTw7V8q5CgHgfKpIorSkFGF99iGpDDmoxwMzsOnigBgOu9hqAfEGUJKxYgFQtQyWZlcTHT34S2lIKiQ8+9Feb+ZUarWS+6Q==
    user: AgBbyE5SItCjVzN5lNmYL0gqtZd3ImFR+g/aFFPLAntFXfU23udvknX0Yvih7bqSnMGNGOmkhBv0KkZLKz7kQswpZ+Ivftn2kOpFLwWEEy9PgGDsNJu930H0UfvZNSXHL3Tht7OWs+xVr30A6mrpP1iVNjuiTfsdtoVVZpPTqivOchdX7It3bt28ts9UcokJbZGCxJ0jOzuZAWHpI6dsJercZNlifxa2h0wRbPZUWm7enbC2mr/Avex5QKigIvBDfxdlzjU8KKR+HARPiWKjIPeK2tmba/C9GZtr0E1zZ/n3pIAcJ4XqyiV+S6buRL4LZFaN8nkjZPjrEjSem4ata+iv7fQH63e0umCQFcW2e7Vec0U2jOhvYQwrMqCvZPS/U801PG5hyx9Ne3aNaBaqo0J/aVUf2HOuBWBJ5zjQ/bNVqzdaXjPuH8ube4U8IGUvgjzA2t99MPQZCwzkOKkaoC+AAkwsDOkK4N37D0IpX3y32S1TpI9e7iJyN0wrF8/6ZZ3M8ieEI6yMsWbVhBtMujFtwnriy+D551rFU+QZMUz4aQ3bg4rzvozNp+oiY37ktWweKkKfoYaZeJdnDw6BPGEuZ26TUqFyjtWoEb/1ZSn65XP8eOtl/ijTrSyxM5M5gJY0Q607Flibn4KNFP+VFkhcNH9ODsNWinCr3I4MNFvdnBOEK2wmUKfCfz1N256pZ3vUwAZlfWnmLui54oc8hl2hxhrBRQ==
  template:
    metadata:
      creationTimestamp: null
      name: trino-users
      namespace: platform
    type: kubernetes.io/opaque

