---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: secret-operator
  namespace: flux-system
spec:
  chart:
    spec:
      chart: secret-operator
      reconcileStrategy: ChartVersion
      sourceRef:
        name: ""
  interval: 1m0s
