---
apiVersion: v1
kind: Pod
metadata:
  name: minio-client
  labels:
    app: minio-client
  namespace: platform
spec:
  selector:
    matchLabels:
      app: minio-client
  restartPolicy: Never
  containers:
    - name: minio-client
      image: docker.io/bitnami/minio-client:2023.5.18-debian-11-r2
      command: ["bash", "-c", "sleep infinity"]
