---
apiVersion: v1
kind: Pod
metadata:
  name: minio-client
  labels:
    app: minio-client
  namespace: platform
spec:
  selector:
    matchLabels:
      app: minio-client
  restartPolicy: Never
  containers:
    - name: minio-client
      image: docker.io/bitnami/minio-client:2023.5.18-debian-11-r2
      command: ["bash", "-c", "sleep infinity"]
---
apiVersion: s3.stackable.tech/v1alpha1
kind: S3Connection
metadata:
  name: minio
  namespace: platform
spec:
  host: minio
  port: 9000
  accessStyle: Path
  credentials:
    secretClass: s3-credentials
  tls:
    verification:
      server:
        caCert:
          secretClass: minio-tls-certificates
