---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: superset-postgres
  namespace: platform
spec:
  chart:
    spec:
      chart: postgresql
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: postgres-repo
      version: 12.1.5
  auth:
    username: superset
    password: superset
    database: superset
  interval: 1m0s
