---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: postgres-repo
  namespace: platform
spec:
  interval: 1m0s
  url: helm repo add bitnami https://charts.bitnami.com/bitnami
