---
apiVersion: s3.stackable.tech/v1alpha1
kind: S3Connection
metadata:
  name: minio
  namespace: platform
spec:
  host: minio
  port: 9000
  accessStyle: Path
  credentials:
    secretClass: minio-s3-credentials
  tls:
    verification:
      server:
        caCert:
          secretClass: minio-tls-certificates