---
apiVersion: v1
kind: Secret
metadata:
  name: trino-users
  namespace: platform
type: kubernetes.io/opaque
stringData:
  admin: "{{ bcrypt(password=trinoAdminPassword) | replace(from="$2b$", to="$2y$") }}"
