---
apiVersion: superset.stackable.tech/v1alpha1
kind: SupersetCluster
metadata:
  name: superset
  namespace: platform
spec:
  image:
    productVersion: 2.1.0
    stackableVersion: 0.0.0-dev
  clusterConfig:
    listenerClass: external-unstable
  credentialsSecret: superset-credentials
  loadExamplesOnInit: false
  nodes:
    roleGroups:
      default:
        config:
          rowLimit: 10000
          webserverTimeout: 300
