---
apiVersion: trino.stackable.tech/v1alpha1
kind: TrinoCluster
metadata:
  name: trino
  namespace: platform
spec:
  image:
    productVersion: "403"
    stackableVersion: "0.0.0-dev"
  clusterConfig:
    catalogLabelSelector:
      matchLabels:
        trino: trino
    authentication:
      method:
        multiUser:
          userCredentialsSecret:
            name: trino-users
    authorization:
      opa:
        configMapName: opa
        package: trino
  coordinators:
    roleGroups:
      default:
        replicas: 1
  workers:
    roleGroups:
      default:
        replicas: 1
