---
apiVersion: trino.stackable.tech/v1alpha1
kind: TrinoCluster
metadata:
  name: trino
  namespace: platform
spec:
  image:
    productVersion: "396"
    stackableVersion: "0.0.0-dev"
  clusterConfig:
    catalogLabelSelector:
      matchLabels:
        trino: trino
  coordinators:
    roleGroups:
      default:
        replicas: 2
  workers:
    roleGroups:
      default:
        replicas: 3
