---
apiVersion: v1
kind: Namespace
metadata:
  name: platform
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: bitnami-repo
  namespace: platform
spec:
  interval: 1m0s
  url: https://charts.bitnami.com/bitnami
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: superset-postgresql
  namespace: platform
spec:
  chart:
    spec:
      chart: postgresql
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: bitnami-repo
      version: 12.5.6
  valuesFrom:
    - kind: ConfigMap
      name: postgresql-values
  interval: 1m0s
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-values
  namespace: platform
data:
  values.yaml: |
    ---
    auth:
      username: superset
      password: superset
      database: superset
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: airflow-postgresql
  namespace: platform
spec:
  chart:
    spec:
      chart: postgresql
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: bitnami-repo
      version: 12.5.6
  valuesFrom:
    - kind: ConfigMap
      name: postgresql-airflow-values
  interval: 1m0s
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-airflow-values
  namespace: platform
data:
  values.yaml: |
    ---
    auth:
      username: airflow
      password: airflow
      database: airflow

