# Default values for piveau.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  searchApiKey: mySearchApiKey
  repoApiKey: myRepoApiKey

tags:
  piveau-hub: true
  piveau-consus: true
  
piveau-hub:
  piveau-hub-repo:
    imageTag: 3.0.10
  piveau-hub-search:
    imageTag: 5.0.1
  piveau-hub-ui:
    imageTag: "v1.13.3"
piveau-consus:
  piveau-consus-exporting-hub:
    imageTag: 4.0.0
  piveau-consus-importing-rdf:
    imageTag: 1.7.3
  piveau-consus-scheduling:
    imageTag: 2.0.2