nameOverride: ""

image: registry.gitlab.com/piveau/hub/piveau-hub-search
imageTag: "4.0.10"
imagePullPolicy: IfNotPresent
imagePullSecrets: [ ]

resources:
  requests:
    cpu: 500m
    memory: 1Gi

extraEnvs: [ ]

externalShape: true

javaOpts: "-XX:MaxRAMPercentage=75.0"

apiKey: "apiKey"

service:
  port: 8080

ingress:
  enabled: false
  annotations:
    kubernetes.io/ingress.class: nginx
  host: piveau.freiburg.stackable.tech
  path: /search/
  pathType: Prefix
  extraHosts: []

cli:
  enabled: false
  # http: { }
  # telnet: { }

elasticsearch:
  nameOverride: search-elasticsearch
  esJavaOpts: "-XX:MaxRAMPercentage=75.0 -Dlog4j2.formatMsgNoLookups=true"
  extraEnvs:
    - name: xpack.security.enabled
      value: "false"
  resources:
    requests:
      cpu: 1
      memory: 2Gi
    limits:
      cpu: 1
      memory: 2Gi
