---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: superset
  namespace: platform
spec:
  chart:
    spec:
      chart: postgresql
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: postgres-repo
      version: 12.1.5
      valuesFrom:
        - kind: ConfigMap
          name: postgresql-values
  interval: 1m0s

