---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: superset-postgresql
  namespace: platform
spec:
  chart:
    spec:
      chart: postgresql
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: postgres-repo
      version: 12.5.6
  valuesFrom:
    - kind: ConfigMap
      name: postgresql-values
  values:
    auth:
      username: superset
      password: superset
      database: superset
  interval: 1m0s

