---
apiVersion: airflow.stackable.tech/v1alpha1
kind: AirflowCluster
metadata:
  name: airflow
  namespace: platform
spec:
  image:
    productVersion: 2.6.1
    stackableVersion: 23.7.0
  clusterConfig:
    executor: CeleryExecutor
    loadExamples: true
    exposeConfig: false
    credentialsSecret: simple-airflow-credentials
    dagsGitSync:
      - repo: https://github.com/stackabletech/datenplatform/
        branch: "freiburg-stable"
        gitFolder: "airflow_dags"
    listenerClass: external-stable
  webservers:
    roleGroups:
      default:
        replicas: 1
  workers:
    config:
      resources:
        cpu:
          min: "400m"
          max: "512Mi"
        memory:
          limit: '1Gi'
    roleGroups:
      default:
        replicas: 3
  schedulers:
    roleGroups:
      default:
        replicas: 2
