apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: piveau-repository
  namespace: platform
spec:
  interval: 1m
  url: https://github.com/stackabletech/datenplatform/tree/main/clusters/FreiburgDEV/platform/piveau
  ref:
    branch: master
