---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: piveau-repository
  namespace: piveau
spec:
  interval: 1m
  url: https://github.com/stackabletech/datenplatform/
  ref:
    branch: main
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: piveau 
  namespace: piveau
spec:
  interval: 5m
  chart:
    spec:
      chart: ./clusters/FreiburgDEV/platform/piveau
      reconcileStrategy: Revision
      version: '1.0.0'
      sourceRef:
        kind: GitRepository
        name: piveau-repository
        namespace: piveau
      interval: 1m
