---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: piveau-repository
  namespace: platform
spec:
  interval: 1m
  url: https://github.com/stackabletech/datenplatform/tree/main/clusters/FreiburgDEV/platform/piveau
  ref:
    branch: master
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: piveau-hub
  namespace: platform
spec:
  interval: 5m
  chart:
    spec:
      chart: Chart.yaml
      reconcileStrategy: ChartVersion
      version: '1.0.0'
      sourceRef:
        kind: GitRepository
        name: piveau-repository
        namespace: platform
      interval: 1m
