---
apiVersion: superset.stackable.tech/v1alpha1
kind: SupersetCluster
metadata:
  name: superset
  namespace: platform
spec:
  image:
    productVersion: 2.1.0
    stackableVersion: 0.0.0-dev
  clusterConfig:
    listenerClass: external-stable
  credentialsSecret: superset-credentials
  loadExamplesOnInit: false
  nodes:
    roleGroups:
      default:
        config:
          rowLimit: 10000
          webserverTimeout: 300
---
apiVersion: v1
kind: Secret
metadata:
  name: superset-credentials
  namespace: platform
type: Opaque
stringData:
  adminUser.username: admin
  adminUser.firstname: Superset
  adminUser.lastname: Admin
  adminUser.email: admin@superset.com
  adminUser.password: admin
  connections.secretKey: superset-postgresql
  connections.sqlalchemyDatabaseUri: postgresql://superset:superset@superset-postgresql.platform.svc.cluster.local/superset

