---
apiVersion: trino.stackable.tech/v1alpha1
kind: TrinoCluster
metadata:
  name: trino
  namespace: platform
spec:
  image:
    productVersion: "403"
    stackableVersion: "0.0.0-dev"
  clusterConfig: 
    catalogLabelSelector:
      matchLabels:
        trino: trino
    authentication:
      - authenticationClass: simple-trino-users
    authorization:
      opa:
        configMapName: opa
        package: trino
  coordinators:
    config:
      queryMaxMemory: 3GB
      resources:
        cpu:
          min: "1"
          max: "4"
        memory:
          limit: '3Gi'
    roleGroups:
      default:
        replicas: 1
  workers:
    config:
      queryMaxMemoryPerNode: 5GB
      resources:
        cpu:
          min: "2"
          max: "4"
        memory:
          limit: '5Gi'
    roleGroups:
      default:
        replicas: 2
---
apiVersion: trino.stackable.tech/v1alpha1
kind: TrinoCatalog
metadata:
  name: tpcds
  labels:
    trino: trino
  namespace: platform
spec:
  connector:
    tpcds: {}
---
apiVersion: trino.stackable.tech/v1alpha1
kind: TrinoCatalog
metadata:
  name: tpch
  labels:
    trino: trino
  namespace: platform
spec:
  connector:
    tpch: {}