---
apiVersion: trino.stackable.tech/v1alpha1
kind: TrinoCluster
metadata:
  name: trino
  namespace: platform
spec:
  image:
    productVersion: "403"
    stackableVersion: "0.0.0-dev"
  clusterConfig:
    listenerClass: external-unstable
    catalogLabelSelector:
      matchLabels:
        trino: trino
    authentication:
      method:
        multiUser:
          userCredentialsSecret:
            name: trino-users
    authorization:
      opa:
        configMapName: opa
        package: trino
  coordinators:
    config:
      queryMaxMemory: 10TB
      resources:
        cpu:
          min: "1"
          max: "4"
        memory:
          limit: '6Gi'
    roleGroups:
      default:
        replicas: 1
  workers:
    config:
      queryMaxMemoryPerNode: 5GB
      resources:
        cpu:
          min: "2"
          max: "4"
        memory:
          limit: '10Gi'
    roleGroups:
      default:
        replicas: 4
---
apiVersion: trino.stackable.tech/v1alpha1
kind: TrinoCatalog
metadata:
  name: tpcds
  labels:
    trino: trino
  namespace: platform
spec:
  connector:
    tpcds: {}
---
apiVersion: trino.stackable.tech/v1alpha1
kind: TrinoCatalog
metadata:
  name: tpch
  labels:
    trino: trino
  namespace: platform
spec:
  connector:
    tpch: {}
---                                                                                                                                                                                                                             
~                                      
