---
apiVersion: trino.stackable.tech/v1alpha1
kind: TrinoCluster
metadata:
  name: trino
  namespace: platform
spec:
  image:
    productVersion: "403"
    stackableVersion: "0.0.0-dev"
  clusterConfig: 
    catalogLabelSelector:
      matchLabels:
        trino: trino
    authentication:
      - authenticationClass: simple-trino-users
    authorization:
      opa:
        configMapName: opa
        package: trino
  coordinators:
    roleGroups:
      default:
        replicas: 1
  workers:
    roleGroups:
      default:
        replicas: 1
---
apiVersion: trino.stackable.tech/v1alpha1
kind: TrinoCatalog
metadata:
  name: tpcds
  labels:
    trino: trino
  namespace: platform
spec:
  connector:
    tpcds: 
      s3:
        inline:
          host: minio
          port: 9000
          pathStyleAccess: true
          secretClass: minio-credentials
          tls:
            verification:
              server:
                caCert:
                  secretClass: minio-tls-certificates
---
apiVersion: trino.stackable.tech/v1alpha1
kind: TrinoCatalog
metadata:
  name: tpch
  labels:
    trino: trino
  namespace: platform
spec:
  connector:
    tpch: {}
