---
apiVersion: authentication.stackable.tech/v1alpha1
kind: AuthenticationClass
metadata:
  name: simple-trino-users
  namespace: platform
spec:
  provider:
    static:
      userCredentialsSecret:
        name: trino-users
---
apiVersion: secrets.stackable.tech/v1alpha1
kind: SecretClass
metadata:
  name: trino-tls
  namespace: platform
spec:
  backend:
    autoTls:
      ca:
        secret:
          name: secret-provisioner-trino-tls-ca
          namespace: platform
        autoGenerate: true
