apiVersion: v1
kind: Service
metadata:
  name: {{ include "piveau-hub-search.fullname" . }}
  labels:
    {{- include "piveau-hub-search.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: default
      protocol: TCP
      name: http
  selector:
    {{- include "piveau-hub-search.selectorLabels" . | nindent 4 }}
