nameOverride: ""

image: registry.gitlab.com/piveau/consus/piveau-consus-exporting-hub
imageTag: "4.0.0"
imagePullPolicy: IfNotPresent
imagePullSecrets: []

resources:
  requests:
    cpu: 1000m
    memory: 2Gi

extraEnvs: []

javaOpts: "-XX:MaxRAMPercentage=75.0"

service:
  port: 8080
