nameOverride: ""

image: registry.gitlab.com/piveau/hub/piveau-hub-repo
imageTag: "2.0.0"
imagePullPolicy: IfNotPresent
imagePullSecrets: [ ]

resources:
  requests:
    cpu: 500m
    memory: 1Gi

extraEnvs: [ ]

javaOpts: "-XX:MaxRAMPercentage=75.0"

externalShape: true

service:
  port: 8080

ingress:
  enabled: false
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: piveau.freiburg.stackable.tech
      paths:
        - path: /repo/
          pathType: Prefix

apiKeys: {}
#  apiKey:
#    - '*'

cli:
  enabled: false
  # http: { }
  # telnet: { }

virtuoso:
  image: openlink/virtuoso-opensource-7
  imageTag: "7.2.8"
  imagePullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 1000m
      memory: 3Gi
    limits:
      cpu: 1000m
      memory: 6Gi
  password: dba
  extraEnvs: [ ]
  service:
    port: 8890
  persistence:
    enabled: false
    size: 100Gi
  ingress:
    enabled: false
    annotations: { }
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
    hosts:
      - host: chart-example.local
        paths:
          - path: /
            pathType: ImplementationSpecific
